/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zepusgwwfoiqejtyjxrm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcHVzZ3d3Zm9pcWVqdHlqeHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwODQ5NDUsImV4cCI6MjA3NzY2MDk0NX0._Di-rjkp5B7Wltq0pGsH0KjWTeLTqHDLof-JYR3jwCU"